version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: WhyNo78Yet?
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data
  server:
    build: server
    ports:
      - "3001:3001"
    volumes:
      - /tmp:/tmp
    environment:
      - POSTGRES_HOST=db
  front:
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - INTERNAL_SERVER_HOSTNAME=server
      - EXTERNAL_SERVER_HOSTNAME=localhost